#ifndef HPCC_MQTT_H
#define HPCC_MQTT_H

#define MQTT_TOPIC_PREFIX "hydrobox."
#define MQTT_TOPIC_IN_PREFIX MQTT_TOPIC_PREFIX "in."
#define MQTT_TOPIC_OUT_PREFIX MQTT_TOPIC_PREFIX "out."
#define MQTT_TOPIC_IN_COMMAND MQTT_TOPIC_IN_PREFIX "command"
#define MQTT_TOPIC_IN_STATUS MQTT_TOPIC_IN_PREFIX "status"
//#define MQTT_TOPIC_OUT_STATUS MQTT_TOPIC_OUT_PREFIX "status"
//#define MQTT_TOPIC_OUT_SENSORS MQTT_TOPIC_OUT_PREFIX "sensor"
#define MQTT_TOPIC_OUT_ACTIONS MQTT_TOPIC_OUT_PREFIX "action"
#define MQTT_TOPIC_OUT_SENSORS "channels/5088d1be-5633-434a-a92b-5651413fa186/messages"

#endif //HPCC_MQTT_H
